services:

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s


  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3001:3000
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

#  frontend:
#    build:
#      context: ../Dockerfile.frontend
#    ports:
#      - "3000:3000"


  shell:
    build:
      context: microfrontends/shell
    ports:
      - 3002:3000
    depends_on:
      - auth
      - profile
      - cards
      - backend

  auth:
    build:
      context: microfrontends/auth
    ports:
      - 3003:3000

  cards:
    build:
      context: microfrontends/cards
    ports:
      - 3004:3000


  profile:
    build:
      context: microfrontends/profile
    ports:
      - 3005:3000
    depends_on:
      - cards
